#!/bin/sh

clear
cat << EOF
















        Please wait... Weston is loading







Note: If you see that the display is stuck on this message
for more than 5 seconds, Weston probably failed to run.
Weston will not run without input devices such as
touchscreen or a mouse. Please check your setup and
attach an input device, and reboot.




EOF

weston --idle-time=0 >> /var/log/weston.log 2>&1
