#!/bin/sh

devices="/dev/mmcblk0p1 /dev/mmcblk0p2 /dev/mmcblk0p3"

case "$1" in
    start )
        for d in $devices
        do
            DEVNAME=$d ACTION=add /etc/udev/scripts/mount.sh > /dev/null 2>&1
        done
    ;;
    stop )
        for d in $devices
        do
            DEVNAME=$d ACTION=remove /etc/udev/scripts/mount.sh > /dev/null 2>&1
        done
    ;;
esac

exit 0;
