#!/bin/sh
# Copyright (C) {2013} Texas Instruments Incorporated - http://www.ti.com/
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# First let's check if we even see a touchscreen device node.  If not
# then bail out.
if [ ! -e /dev/input/touchscreen0 ]
then
    exit
fi

# Import Important System Environment Variables
SCRIPTS=/etc/profile.d/*.sh

for f in $SCRIPTS
do
    source $f
done

if [ ! -f $TSLIB_CALIBFILE ] ; then
    echo    "Calibrating touchscreen (first time only)"
    echo
    echo    "*** To continue, please complete the touchscreen calibration"
    echo -n "*** by touching the crosshairs on the LCD screen"
    ts_calibrate
    echo "."

    # If we create a pointercal file and it was not in /etc/pointercal
    # let's copy it there as well if it does not already exist.  This is so
    # that running other applications that look for /etc/pointercal and
    # without TSLIB_CALIBFILE set will still get the right calibration.
    # TODO: can we just globally export TSLIB_CALIBFILE?
    if [ ! -f /etc/pointercal -a -f $TSLIB_CALIBFILE ]
    then
        cp $TSLIB_CALIBFILE /etc/pointercal
    fi
fi
